---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/o-cloud-operator-konflux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "main" &&
      !event_title.contains("[BRANCH-CUT]") &&
      (
        'catalog/4.20/***'.pathChanged() ||
        '.tekton/fbc-pipeline-4-20.yaml'.pathChanged() ||
        '.tekton/images-mirror-set-4-20.yaml'.pathChanged() ||
        '.tekton/o-cloud-manager-fbc-4-20-pull-request.yaml'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: o-cloud-manager-fbc-4-20
    appstudio.openshift.io/component: o-cloud-manager-fbc-4-20
    pipelines.appstudio.openshift.io/type: build
  name: o-cloud-manager-fbc-4-20-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-fbc-4-20:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: catalog/4.20/Dockerfile.catalog
    - name: hermetic
      value: "true"
    - name: additional-tags
      value: []
    - name: ocp-version
      value: "4.20"
    - name: ocp-version-dashed
      value: "4-20"
  pipelineRef:
    name: fbc-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-o-cloud-manager-fbc-4-20
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
