---
name: YAML Lint

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: |
          find . -name '*.yaml' -o -name '*.yml' \
            | grep -v './telco5g-konflux/' \
            | grep -v './bundles/v0.1/oran-o2ims/' \
            | grep -v './bundles/v0.2/oran-o2ims/' \
            | xargs yamllint -c .yamllint.yaml -f github
